# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  smoke-test:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - run: apk add --update curl
      - run:
          - name: check if website exists
          - command: |
              if curl -s --head "https://google.com" 
              then
                echo "It worked!"
              else
                echo "It failed"
              fi

workflows:
  smoke-test:
    jobs:
      - smoke-test
